package com.shah.javacoretutorials.model;

import java.util.List;

public class Fruits {

    public final static List<String> fruits = List.of("Banana", "Banana", "Bilberry", "Blackberry", "Blackcurrant", "Black sapote", "Blueberry", "Boysenberry", "Breadfruit", "Buddha's hand (fingered citron)", "Cactus pear", "Canistel", "Cempedak", "Cherimoya (Custard Apple)", "Cherry", "Chico fruit", "Cloudberry", "Coco De Mer", "Coconut", "Crab apple", "Cranberry", "Currant", "Damson", "Date", "Dragonfruit (or Pitaya)", "Durian", "Egg Fruit", "Elderberry", "Feijoa", "Fig", "Goji berry", "Gooseberry", "Grape", "Abiu", "Açaí", "Acerola", "Ackee", "African cucumber", "Apple", "Apricot", "Avocado", "Raisin", "Grapefruit", "Grewia asiatica (phalsa or falsa)", "Guava", "Hala Fruit", "Honeyberry", "Huckleberry", "Jabuticaba", "Jackfruit", "Jambul", "Japanese plum", "Jostaberry", "Jujube", "Juniper berry", "Kaffir Lime", "Kiwano (horned melon)", "Kiwifruit", "Kumquat", "Lemon", "Lime", "Loganberry", "Longan", "Loquat", "Lulo", "Lychee", "Magellan Barberry", "Mamey Apple", "Mamey Sapote", "Mango", "Mangosteen", "Marionberry", "Melon", "Cantaloupe", "Galia melon", "Honeydew", "Mouse Melon", "Watermelon", "Miracle fruit", "Monstera deliciosa", "Mulberry", "Nance", "Nectarine", "Orange", "Blood orange", "Clementine", "Mandarine", "Tangerine", "Papaya", "Passionfruit", "Peach", "Pear", "Persimmon", "Plantain", "Plum", "Prune (dried plum)", "Pineapple", "Pineberry", "Plumcot (or Pluot)", "Pomegranate", "Pomelo", "Purple mangosteen", "Quince", "Raspberry", "Salmonberry", "Rambutan (or Mamin Chino)", "Redcurrant", "Rose apple", "Salal berry", "Salak", "Satsuma", "Shine Muscat or Vitis Vinifera", "Sloe or Hawthorn Berry", "Soursop", "Star apple", "Star fruit", "Strawberry", "Surinam cherry", "Tamarillo", "Tamarind", "Tangelo", "Tayberry", "Tomato", "Ugli fruit", "White currant", "White sapote", "Yuzu", "Bell pepper", "Chile pepper", "Corn kernel", "Cucumber", "Eggplant", "Jalapeño", "Olive", "Pea", "Pumpkin", "Squash", "Tomato", "Zucchini");

    public final static List<String> fruits2 = List.of("Juniper berry", "Juniper berry", "Olive", "Pea", "Kaffir Lime", "Abiu", "Banana", "Feijoa", "Lemon", "Mouse Melon", "Goji berry", "Yuzu", "Galia melon", "Cactus pear", "Cactus pear", "Nance", "Durian", "Egg Fruit", "Quince", "Raisin", "Salmonberry", "Tangerine", "Zucchini", "Ugli fruit", "White sapote", "Hala Fruit");

    public final static List<Integer> numbers = List.of(9, 3, 2, 5, 7, 9, 1);
}
